Repository kuronosec/zikuani, pull requests merged in 2025-01, with the labels that each got.

#51 Merge hackathon branch into dev
  .gitignore
  contracts/deployed-contracts/ethereum.json
  contracts/interfaces/IZKFirmaDigitalCredentialIssuer.sol
  contracts/scripts/deploy_output_test.json
  contracts/scripts/utils/ZKFirmaDigitalCredentialIssuerDeployHelper.ts
  contracts/src/MedicalCertificateIssuer.sol
  src/docs/hackathon-dif-2024.md
  src/encryption.py
  src/ethereum_utils.py
  src/translations_en.ts
Labels: enhancement

#54 Add translation code to the app
  src/main.py
Labels: enhancement

#55 Connect VCs with privadoID wallet
  assets/zk-firma-digital-vocab.md
  assets/zk-firma-digital.json
  assets/zk-firma-digital.jsonld
  contracts/deployed-contracts/ethereum.json
  contracts/scripts/deploy_output_test.json
  contracts/src/ZKFirmaDigitalCredentialIssuer.sol
  contracts/src/verifier.sol
Labels: enhancement

#57 Improve voting contract and contract deployment scripts
  contracts/deployed-contracts/ethereum.json
  contracts/scripts/createVC.ts
  contracts/scripts/deploy.ts
  contracts/scripts/deployVotingContract.ts
  contracts/scripts/getVC.ts
  contracts/scripts/revokeVC.ts
  contracts/src/ZKFirmaDigitalVote.sol
Labels: Smart Contracts

#59 Hardware Requirements #47
  README.md
Labels: documentation, enhancement

#60 Improve translation config
  builder/entrypoint_debian.sh
  src/authentication_window.py
  src/main.py
  src/translations_en.ts
Labels: enhancement
